In [6]:
import numpy as np
a = np.array([20,40,60,80])
print(np.append(a,90))  # insert at last

[20 40 60 80 90]


In [3]:
a = np.array([[20,40],[60,80]])
print(np.append(a,[90,100]))  # in 2 dimensional it converts the array to 1d

[ 20  40  60  80  90 100]


In [13]:
a = np.array([[20,40],[60,80]])
print(np.insert(a,1,[50,60], axis = 1))  # insert in a position/array, index, value

[[20 50 40]
 [60 60 80]]


In [14]:
a = np.array([[20,40],[60,80]])
print(np.insert(a,1,[50,60], axis = 0))  

[[20 40]
 [50 60]
 [60 80]]


In [16]:
print(a)
print(np.delete(a,1))

[[20 40]
 [60 80]]
[20 60 80]


In [18]:
print(a)
print(np.delete(a,1,axis=1))

[[20 40]
 [60 80]]
[[20]
 [60]]


In [17]:
print(a)
print(np.delete(a,1,axis=0))

[[20 40]
 [60 80]]
[[20 40]]
