In [13]:
import numpy as np
a = [30, 40, 50]
b = [5, 5, 3]
print(a+b)

[30, 40, 50, 5, 5, 3]


In [14]:
# concatenate
arr1 = np.array([30,40,50])
arr2 = np.array([5, 5, 3])
print(np.concatenate([arr1,arr2]))

[30 40 50  5  5  3]


In [16]:
arr1 = np.array([[30,40],[50,60]])
arr2 = np.array([[5, 5], [3,3]])
"""print(np.concatenate([arr1,arr2]))  # by default axis = 0 / verticsl"""
print(np.concatenate([arr1,arr2], axis = 1))  # horizontal

[[30 40  5  5]
 [50 60  3  3]]


In [18]:
print(np.hstack([arr1,arr2]))  # horizontal

[[30 40  5  5]
 [50 60  3  3]]


In [19]:
print(np.vstack([arr1,arr2]))  # vertical

[[30 40]
 [50 60]
 [ 5  5]
 [ 3  3]]


In [6]:
import numpy as np
a = np.array([20,40,30,40,10,20])
b = np.array_split(a,3)  # split in 3 parts
print(b[1])

[30 40]


In [9]:
a = np.array([[20,40,30],[40,10,20]])
b = np.array_split(a,2) 
print(b)

[array([[20, 40, 30]]), array([[40, 10, 20]])]
