In [4]:
import numpy as np
arr1 = np.array([30, 40, 60, 20, 10])
arr2 = np.array([20, 30, 10, -15, 20])
print(arr1+arr2)
print(np.add(arr1,arr2))

[50 70 70  5 30]
[50 70 70  5 30]


In [5]:
arr1 = np.array([[30, 40], [20, 10]])
arr2 = np.array([[20, 30], [-15, 20]])
print(arr1+arr2)
print(np.add(arr1,arr2))

[[50 70]
 [ 5 30]]
[[50 70]
 [ 5 30]]


In [7]:
arr1 = np.array([[30, 40], [20, 10]])
arr2 = np.array([[20, 30], [-15, 20]])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[[ 10  10]
 [ 35 -10]]
[[ 10  10]
 [ 35 -10]]


In [8]:
arr1 = np.array([[30, 40], [20, 10]])
arr2 = np.array([[20, 30], [-15, 20]])
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[[ 600 1200]
 [-300  200]]
[[ 600 1200]
 [-300  200]]


In [9]:
arr1 = np.array([[30, 40], [20, 10]])
arr2 = np.array([[20, 30], [-15, 20]])
print(arr1/arr2)
print(np.divide(arr1,arr2))

[[ 1.5         1.33333333]
 [-1.33333333  0.5       ]]
[[ 1.5         1.33333333]
 [-1.33333333  0.5       ]]


In [10]:
arr1 = np.array([[30, 40], [20, 10]])
arr2 = np.array([3])
print(np.power(arr1,arr2))

[[27000 64000]
 [ 8000  1000]]


In [17]:
arr1 = np.array([9, 16, 121, 144])
arr2 = np.sqrt(arr1)
print(arr2.astype(int))  # type conversion

[ 3  4 11 12]
