In [9]:
import numpy as np
a = np.array([20,30,40])
b = np.array([60, 70, 80])
c = 12
print(a)
print(b)
# mathematical operations working
print(a*b)
print(a*c)

[20 30 40]
[60 70 80]
[1200 2100 3200]
[240 360 480]


In [11]:
a = np.array([40,50,"60"])
print(a)  # fixed one data type

['40' '50' '60']


In [16]:
a = np.array([[40,50],[60,70]])  # size must be equal in array
print(a)

[[40 50]
 [60 70]]


In [12]:
l1 = [[20,30],[40,50,60]]
print(l1)

[[20, 30], [40, 50, 60]]
